---
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache: pip

env:
  - DJANGO='>= 1.11, < 1.12'
  - DJANGO='>= 2.0, < 2.1'

matrix:
  exclude:
    # Django dropped support for Python 2 in versions 2.0 and above
    - python: 2.7
      env: DJANGO='>= 2.0, < 2.1'

install:
  - pip install --upgrade pip
  - pip install "Django $DJANGO"
  - python setup.py install
  - pip install -r requirements/ci.txt

script:
  - flake8
  - coverage run -m pytest

after_success: codecov

# Add job to deploy to PyPI after tests complete
jobs:
  include:
    - stage: PyPI release
      if: tag IS present

      python: 3.6
      env: DJANGO='>= 2.0, < 2.1'

      # Skip usual steps
      install: skip
      script: skip
      # Can't just skip after_success because then the deployment gets skipped.
      # Issue: https://github.com/travis-ci/travis-ci/issues/8337
      after_success: echo "Skipping 'after_success' for deployment."

      deploy:
        provider: pypi
        user: cdriehuys
        password:
          secure: "qiqX4jeX8JbUu4sOCQ0D7+KNl2O4upEqHWUE6y7JkJf7FfJdbucYvVpEk2AyONRFsHcZIzDUAD6j8iKxeJGei/HoD6nrlqrmMmAz/fdnpwCMI9/VWTNoend7e/6HR9nkc6KqYVZ4F+UrEg6tlai/L/ZiL9T+Ro6FKe2DnorYxbo6lyV4RAD1nRpBrRijXx9AjacaYUsp4AvAbfiYoJW2Q/x68Ghud+pSGQfg3x1X31/kInCxgGiDmDGASB/DFEUUnSujf8Ij7D+ZRVRdopyjCUmPNtFHI8iRMuzzGh2aN2Fm9z87jp2NwWQsJB5T3ITMUBpba/G/9WZ/tZfKeXwht7kYPZoHUEhGvFn5YooBY4EKLo0QtV2CtBPWJxSm6owjNc+my51EV8DYeehK+CxCRRrP+q/eO68Yg8+M8GgCcADVTaN7i4qngZZMYiyP4F4eC4S5oZ6xbGZgFrPhNLfG4dGuCXSy1iJy0Rb7Gf+e7FWsPYV9r/3kMeFp617waxYQsibjjTXCyQaRSpWJf7SgWMk9VRR1L9agtEWKKkyWIg7AbzrysK4TVQJTx0T0mfzZtM+NEesIB9NI4X8aUqSiGwDoUKMA3DHQjVpxVC1pVbnuZh8qpiZnPUtApKSn4Em9hPaMMfT7f2jvm/1v6EFm4RS8RBij3j+txvirRuEm2mY="
        distributions: sdist bdist_wheel
        on:
          tags: yes

notifications:
  email:
    on_success: never
    on_failure: always
